publish_to: none
version: 0.1.4

name: bakkugi
description: none

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  excel: ^4.0.3
  file_picker: ^8.0.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  intl: ^0.19.0
  package_info_plus: ^8.0.0
  path_provider: ^2.1.3
  window_manager: ^0.3.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Cascadia Code
      fonts:
        - asset: assets/fonts/CascadiaCode-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/CascadiaCode-Regular.ttf
          weight: 400
        - asset: assets/fonts/CascadiaCode-Bold.ttf
          weight: 700